In [ ]:
from google.colab import files
Uploaded = files.upload()
print(Uploaded)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv('Sample data.csv')
df

<ipython-input-5-474099b5e349>:1: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('Sample data.csv')

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,first_attempted,rider_reached_customer_gate,delivery_attempted,delivered,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,NaN,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,NaN,21-03-2024 09:59:00,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,NaN,10-03-2024 07:38:30,NaN,10-03-2024 07:39:00,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,NaN,16-03-2024 17:04:13,NaN,16-03-2024 17:04:00,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,NaN,21-03-2024 15:02:43,NaN,21-03-2024 15:06:00,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,09-03-2024 15:10:25,NaN,09-03-2024 15:10:00,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC

In [ ]:
# Created to track how many orders weree attempted before getting delivered.
df['order_Reattempt']= np.where(df['delivery_attempted'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,rider_reached_customer_gate,delivery_attempted,delivered,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT,order_Reattempt
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,NaN,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,21-03-2024 09:59:00,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,10-03-2024 07:38:30,NaN,10-03-2024 07:39:00,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,16-03-2024 17:04:13,NaN,16-03-2024 17:04:00,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,21-03-2024 15:02:43,NaN,21-03-2024 15:06:00,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,09-03-2024 15:10:25,NaN,09-03-2024 15:10:00,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0

In [ ]:
# Created to check how many orders were delivered directly without getting cancelled after delivery.
df['is_Delivered']=np.where(df['LATESTORDERSTATUS']=='DELIVERED',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,delivery_attempted,delivered,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT,order_Reattempt,is_Delivered
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,21-03-2024 09:59:00,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,NaN,10-03-2024 07:39:00,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,NaN,16-03-2024 17:04:00,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,NaN,21-03-2024 15:06:00,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,09-03-2024 15:10:00,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1

In [ ]:
df.columns

Index(['orderid', 'cust_pin', 'SHOPID', 'store_city', 'customer_city_bucket',
       'store_type', 'City_Bucket', 'LATESTORDERSTATUS', 'systemDSP',
       'forwardDSP', 'pendencyFlag', 'pendencyType', 'orderDateXls',
       'firstTatDate', 'secondTatDate', 'created_ts_IST', 'booked',
       'rider_reached_store', 'verified', 'first_shc', 'last_shc', 'billed',
       'firstpacked', 'lastpacked', 'first_rts', 'last_rts', 'firstshipped',
       'lastshipped', 'first_ofd', 'last_ofd', 'first_attempted',
       'rider_reached_customer_gate', 'delivery_attempted', 'delivered',
       'cancelled', 'return_pending', 'return_requested', 'firstTAT',
       'secondTAT', 'latestTAT', 'order_Reattempt', 'is_Delivered'],
      dtype='object')

In [ ]:
# Created to track how many orders were cancelled
df['is_cancelled']= np.where(df['pendencyFlag']== 'cancelled',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,delivered,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT,order_Reattempt,is_Delivered,is_cancelled
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,21-03-2024 09:59:00,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,10-03-2024 07:39:00,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,16-03-2024 17:04:00,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,21-03-2024 15:06:00,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,09-03-2024 15:10:00,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1,0

In [ ]:
# Created to trackorders which are pending
df['pending']=np.where(df['pendencyFlag']=='pending',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,cancelled,return_pending,return_requested,firstTAT,secondTAT,latestTAT,order_Reattempt,is_Delivered,is_cancelled,pending
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,16-03-2024 21:02:12,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0,1,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,12-03-2024 03:37:10,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0,1,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,26-02-2024 18:23:26,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0,1,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,27-02-2024 19:42:53,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0,1,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,02-03-2024 19:03:01,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,NaN,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,NaN,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,NaN,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1,0,0

In [ ]:
# Created to track the orders asking to be returned after delivery
df['Post_delivery_returns']= np.where(df['pendencyFlag']=='post_Delivery_Return',1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,return_pending,return_requested,firstTAT,secondTAT,latestTAT,order_Reattempt,is_Delivered,is_cancelled,pending,Post_delivery_returns
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,2024-03-16 22:53:00 UTC,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0,1,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0,1,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0,1,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,2024-02-27 20:49:00 UTC,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0,1,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,NaN,NaN,2024-03-02 19:35:00 UTC,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,NaN,NaN,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1,0,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,NaN,NaN,2024-03-16 20:26:00 UTC,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,NaN,NaN,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,NaN,NaN,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1,0,0,0

In [ ]:
# Created to track the first TAT Adherence
df['Formatted_created_date'] = pd.to_datetime(df['created_ts_IST']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['Formatted_created_date'] = pd.to_datetime(df['Formatted_created_date'])
df['firstTAT']=pd.to_datetime(df['firstTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['firstTAT']=pd.to_datetime(df['firstTAT'])

<ipython-input-12-9faab46d3866>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Formatted_created_date'] = pd.to_datetime(df['created_ts_IST']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
# Created to track the difference between First TAT and created date
df['create_to_f_tat_diff'] = np.where(df['Formatted_created_date'].notna() & df['firstTAT'].notna(),
np.maximum ((df['firstTAT'] - df['Formatted_created_date']).dt.total_seconds() / 60,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,firstTAT,secondTAT,latestTAT,order_Reattempt,is_Delivered,is_cancelled,pending,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 22:53:00,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0,1,0,0,2024-03-16 20:53:04,119.933333
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 11:45:00,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0,1,0,0,2024-03-12 03:33:00,492.000000
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 20:11:00,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0,1,0,0,2024-02-26 18:21:16,109.733333
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 20:49:00,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0,1,0,0,2024-02-27 18:49:30,119.500000
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 19:35:00,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0,1,0,0,2024-03-02 17:45:46,109.233333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 12:26:00,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1,0,0,0,2024-03-21 09:26:22,179.633333
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-10 13:00:00,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1,0,0,0,2024-03-09 22:44:55,855.083333
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 20:26:00,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1,0,0,0,2024-03-16 16:27:34,238.433333
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 16:48:00,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1,0,0,0,2024-03-21 13:48:22,179.633333
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 17:47:00,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1,0,0,0,2024-03-09 14:47:19,179.683333

In [ ]:
# Created the bucket for first TAT and Created TAT diffarence
df['Created_to_F_TAT_Diff_0_to_2_hrs']=np.where(df['create_to_f_tat_diff']<121,1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,secondTAT,latestTAT,order_Reattempt,is_Delivered,is_cancelled,pending,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 22:54:00 UTC,2024-03-16 22:54:00 UTC,0,0,1,0,0,2024-03-16 20:53:04,119.933333,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 11:45:00 UTC,2024-03-12 11:45:00 UTC,0,0,1,0,0,2024-03-12 03:33:00,492.000000,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 20:11:00 UTC,2024-02-26 20:11:00 UTC,0,0,1,0,0,2024-02-26 18:21:16,109.733333,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 20:49:00 UTC,2024-02-27 21:05:00 UTC,0,0,1,0,0,2024-02-27 18:49:30,119.500000,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 19:37:00 UTC,2024-03-02 19:37:00 UTC,0,0,1,0,0,2024-03-02 17:45:46,109.233333,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 12:26:00 UTC,2024-03-21 12:26:00 UTC,0,1,0,0,0,2024-03-21 09:26:22,179.633333,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-10 13:00:00 UTC,2024-03-10 13:00:00 UTC,0,1,0,0,0,2024-03-09 22:44:55,855.083333,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 20:27:00 UTC,2024-03-16 20:27:00 UTC,0,1,0,0,0,2024-03-16 16:27:34,238.433333,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 16:48:00 UTC,2024-03-21 16:48:00 UTC,0,1,0,0,0,2024-03-21 13:48:22,179.633333,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 17:47:00 UTC,2024-03-09 17:47:00 UTC,0,1,0,0,0,2024-03-09 14:47:19,179.683333,0

In [ ]:
#Created the buckeat for first TAT and created TAT differnce
df['Created_to_F_TAT_Diff_2_to_4_hrs']=np.where((df['create_to_f_tat_diff']<120) & (df['create_to_f_tat_diff']<241),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,latestTAT,order_Reattempt,is_Delivered,is_cancelled,pending,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 22:54:00 UTC,0,0,1,0,0,2024-03-16 20:53:04,119.933333,1,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 11:45:00 UTC,0,0,1,0,0,2024-03-12 03:33:00,492.000000,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 20:11:00 UTC,0,0,1,0,0,2024-02-26 18:21:16,109.733333,1,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 21:05:00 UTC,0,0,1,0,0,2024-02-27 18:49:30,119.500000,1,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 19:37:00 UTC,0,0,1,0,0,2024-03-02 17:45:46,109.233333,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 12:26:00 UTC,0,1,0,0,0,2024-03-21 09:26:22,179.633333,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-10 13:00:00 UTC,0,1,0,0,0,2024-03-09 22:44:55,855.083333,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 20:27:00 UTC,0,1,0,0,0,2024-03-16 16:27:34,238.433333,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 16:48:00 UTC,0,1,0,0,0,2024-03-21 13:48:22,179.633333,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 17:47:00 UTC,0,1,0,0,0,2024-03-09 14:47:19,179.683333,0,0

In [ ]:
# Created the bucket for first TAT and Created TAT differnece
df['four_8hrs']=np.where((df['create_to_f_tat_diff']>=241) & (df['create_to_f_tat_diff']<=480),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,order_Reattempt,is_Delivered,is_cancelled,pending,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0,2024-03-16 20:53:04,119.933333,1,1,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0,2024-03-12 03:33:00,492.000000,0,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0,2024-02-26 18:21:16,109.733333,1,1,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0,2024-02-27 18:49:30,119.500000,1,1,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0,2024-03-02 17:45:46,109.233333,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-21 09:26:22,179.633333,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-09 22:44:55,855.083333,0,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-16 16:27:34,238.433333,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,1,0,0,0,2024-03-21 13:48:22,179.633333,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,0,0,0,2024-03-09 14:47:19,179.683333,0,0,0

In [ ]:
# Created the bukets for firts TAT and Created TAT differnce
df['eight_24hrs']=np.where((df['create_to_f_tat_diff']>=481) & (df['create_to_f_tat_diff']<=1440),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,is_Delivered,is_cancelled,pending,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0,2024-03-16 20:53:04,119.933333,1,1,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0,2024-03-12 03:33:00,492.000000,0,0,0,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0,2024-02-26 18:21:16,109.733333,1,1,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0,2024-02-27 18:49:30,119.500000,1,1,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0,2024-03-02 17:45:46,109.233333,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-21 09:26:22,179.633333,0,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-09 22:44:55,855.083333,0,0,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-16 16:27:34,238.433333,0,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,0,0,0,2024-03-21 13:48:22,179.633333,0,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,2024-03-09 14:47:19,179.683333,0,0,0,0

In [ ]:
# Created the bucket for first TAT and Created TAT difference
df['twentyfour_48hrs']=np.where((df['create_to_f_tat_diff']>=1441) &(df['create_to_f_tat_diff']<=2880),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,is_cancelled,pending,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs,twentyfour_48hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,2024-03-16 20:53:04,119.933333,1,1,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,0,0,2024-03-12 03:33:00,492.000000,0,0,0,1,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,2024-02-26 18:21:16,109.733333,1,1,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,2024-02-27 18:49:30,119.500000,1,1,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,2024-03-02 17:45:46,109.233333,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,2024-03-21 09:26:22,179.633333,0,0,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,0,2024-03-09 22:44:55,855.083333,0,0,0,1,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,2024-03-16 16:27:34,238.433333,0,0,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,2024-03-21 13:48:22,179.633333,0,0,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,2024-03-09 14:47:19,179.683333,0,0,0,0,0

In [ ]:
df['greaterthan_48hrs']=np.where((df['create_to_f_tat_diff']>=2881) & (df['create_to_f_tat_diff']<=5760),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,pending,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-03-16 20:53:04,119.933333,1,1,0,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-03-12 03:33:00,492.000000,0,0,0,1,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-02-26 18:21:16,109.733333,1,1,0,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-02-27 18:49:30,119.500000,1,1,0,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,2024-03-02 17:45:46,109.233333,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,2024-03-21 09:26:22,179.633333,0,0,0,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,2024-03-09 22:44:55,855.083333,0,0,0,1,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,2024-03-16 16:27:34,238.433333,0,0,0,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,2024-03-21 13:48:22,179.633333,0,0,0,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,2024-03-09 14:47:19,179.683333,0,0,0,0,0,0

In [ ]:
# Created to track the Orders whose terninal status is delivered and cancelled after delivery
df['NetDelivered']=np.where(df['delivered'].notna,1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Post_delivery_returns,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs,NetDelivered
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-03-16 20:53:04,119.933333,1,1,0,0,0,0,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,2024-03-12 03:33:00,492.000000,0,0,0,1,0,0,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-02-26 18:21:16,109.733333,1,1,0,0,0,0,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-02-27 18:49:30,119.500000,1,1,0,0,0,0,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,2024-03-02 17:45:46,109.233333,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,2024-03-21 09:26:22,179.633333,0,0,0,0,0,0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,2024-03-09 22:44:55,855.083333,0,0,0,1,0,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,2024-03-16 16:27:34,238.433333,0,0,0,0,0,0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,2024-03-21 13:48:22,179.633333,0,0,0,0,0,0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,2024-03-09 14:47:19,179.683333,0,0,0,0,0,0,1

In [ ]:
df['delivered']= pd.to_datetime(df['delivered']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['firstTAT']= pd.to_datetime (df['firstTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')

<ipython-input-21-4060f26381e1>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['delivered']= pd.to_datetime(df['delivered']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
# Created to track first TAT Adherence
df['First_SLA_Adherence'] = np.where(df['NetDelivered'] == 1, np.where(df['delivered'] <= df['firstTAT'],1,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Formatted_created_date,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs,NetDelivered,First_SLA_Adherence
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-16 20:53:04,119.933333,1,1,0,0,0,0,1,0.0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,2024-03-12 03:33:00,492.000000,0,0,0,1,0,0,1,0.0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-26 18:21:16,109.733333,1,1,0,0,0,0,1,0.0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-02-27 18:49:30,119.500000,1,1,0,0,0,0,1,0.0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,2024-03-02 17:45:46,109.233333,1,1,0,0,0,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-21 09:26:22,179.633333,0,0,0,0,0,0,1,1.0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,2024-03-09 22:44:55,855.083333,0,0,0,1,0,0,1,1.0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,2024-03-16 16:27:34,238.433333,0,0,0,0,0,0,1,1.0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,2024-03-21 13:48:22,179.633333,0,0,0,0,0,0,1,1.0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,2024-03-09 14:47:19,179.683333,0,0,0,0,0,0,1,1.0

In [ ]:
df['delivered']= pd.to_datetime(df['delivered']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['secondTAT']= pd.to_datetime (df['secondTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
# Created to track second TAT Adherence
df['Second_SLA_Adherence'] = np.where(df['NetDelivered'] == 1, np.where(df['delivered'] <= df['secondTAT'],1,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,create_to_f_tat_diff,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,119.933333,1,1,0,0,0,0,1,0.0,0.0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,492.000000,0,0,0,1,0,0,1,0.0,0.0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,109.733333,1,1,0,0,0,0,1,0.0,0.0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,119.500000,1,1,0,0,0,0,1,0.0,0.0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,109.233333,1,1,0,0,0,0,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,179.633333,0,0,0,0,0,0,1,1.0,1.0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,855.083333,0,0,0,1,0,0,1,1.0,1.0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,238.433333,0,0,0,0,0,0,1,1.0,1.0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,179.633333,0,0,0,0,0,0,1,1.0,1.0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,179.683333,0,0,0,0,0,0,1,1.0,1.0

In [ ]:
df['delivered']= pd.to_datetime(df['delivered']).dt.strftime('%Y-%m-%d %H:%M:%S')
df['latestTAT']= pd.to_datetime (df['latestTAT']).dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
#Created to track Latest TAT Adherence
df['Latest_SLA_Adherence'] = np.where(df['NetDelivered'] == 1, np.where(df['delivered'] <= df['latestTAT'],1,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Created_to_F_TAT_Diff_0_to_2_hrs,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,1,0,0,0,0,1,0.0,0.0,0.0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0,0,1,0.0,0.0,0.0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,1,0,0,0,0,1,0.0,0.0,0.0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,1,0,0,0,0,1,0.0,0.0,0.0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,1,0,0,0,0,1,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,0,0,0,1,1.0,1.0,1.0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,0,1,0,0,1,1.0,1.0,1.0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,0,0,0,1,1.0,1.0,1.0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,0,0,0,1,1.0,1.0,1.0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,0,0,0,1,1.0,1.0,1.0

In [ ]:
#Created to track total orders count
df['Count']=np.where(df['orderid'].notna,1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Created_to_F_TAT_Diff_2_to_4_hrs,four_8hrs,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence,Count
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,0.0,0.0,0.0,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0,1,0.0,0.0,0.0,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,0.0,0.0,0.0,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,0.0,0.0,0.0,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,0,1,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,0,0,1,1.0,1.0,1.0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,0,0,1,1.0,1.0,1.0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,0,0,1,1.0,1.0,1.0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,0,0,1,1.0,1.0,1.0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,0,0,1,1.0,1.0,1.0,1

In [ ]:
# Created to track where the actual pendency is
df['pre_store_pending']=np.where((df['pendencyFlag']=='pending') & (df['pendencyFlag']=='pre-verification'),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,four_8hrs,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence,Count,pre_store_pending
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,0.0,0.0,0.0,1,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0,1,0.0,0.0,0.0,1,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,0.0,0.0,0.0,1,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,0.0,0.0,0.0,1,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,0,1,0.0,0.0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,0,1,1.0,1.0,1.0,1,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,0,0,1,1.0,1.0,1.0,1,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,0,1,1.0,1.0,1.0,1,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,0,1,1.0,1.0,1.0,1,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,0,1,1.0,1.0,1.0,1,0

In [ ]:
# Created to track where the actual pendency is
df['prebill']=np.where((df['pendencyFlag']=='pending') & (df['pendencyFlag']=='pre-Billing'),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,eight_24hrs,twentyfour_48hrs,greaterthan_48hrs,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence,Count,pre_store_pending,prebill
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0.0,0.0,0.0,1,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,0,0,1,0.0,0.0,0.0,1,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0.0,0.0,0.0,1,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0.0,0.0,0.0,1,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0.0,0.0,0.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1.0,1.0,1.0,1,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,0,0,1,1.0,1.0,1.0,1,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,1,1.0,1.0,1.0,1,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,1,1.0,1.0,1.0,1,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1.0,1.0,1.0,1,0,0

In [ ]:
# Created to track where the actual pendency is
df['postShip_Pending']= np.where((df['pendencyFlag']=='pending') &(df['pendencyType']=='in-Transit'),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,twentyfour_48hrs,greaterthan_48hrs,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence,Count,pre_store_pending,prebill,postShip_Pending
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0.0,0.0,0.0,1,0,0,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0.0,0.0,0.0,1,0,0,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0.0,0.0,0.0,1,0,0,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0.0,0.0,0.0,1,0,0,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0.0,0.0,0.0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1.0,1.0,1.0,1,0,0,0
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,1.0,1.0,1.0,1,0,0,0
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,1,1.0,1.0,1.0,1,0,0,0
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,1,1.0,1.0,1.0,1,0,0,0
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1.0,1.0,1.0,1,0,0,0

In [ ]:
df['Store_Pushed']= np.where(df['SHOPID'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,greaterthan_48hrs,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence,Count,pre_store_pending,prebill,postShip_Pending,Store_Pushed
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0.0,0.0,0.0,1,0,0,0,1
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,1,0.0,0.0,0.0,1,0,0,0,1
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0.0,0.0,0.0,1,0,0,0,1
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0.0,0.0,0.0,1,0,0,0,1
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0.0,0.0,0.0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,1.0,1.0,1.0,1,0,0,0,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,1.0,1.0,1.0,1,0,0,0,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,1,1.0,1.0,1.0,1,0,0,0,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,1,1.0,1.0,1.0,1,0,0,0,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,1.0,1.0,1.0,1,0,0,0,1

In [ ]:
# Created to tarck where the actual pandency is
df['DSP_Assigned']=np.where(df['forwardDSP'].notna(),1,0)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,NetDelivered,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence,Count,pre_store_pending,prebill,postShip_Pending,Store_Pushed,DSP_Assigned
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0.0,0.0,0.0,1,0,0,0,1,0
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,0.0,0.0,0.0,1,0,0,0,1,0
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0.0,0.0,0.0,1,0,0,0,1,0
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0.0,0.0,0.0,1,0,0,0,1,0
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0.0,0.0,0.0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,1.0,1.0,1.0,1,0,0,0,1,1
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,1.0,1.0,1.0,1,0,0,0,1,1
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,1.0,1.0,1.0,1,0,0,0,1,1
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,1.0,1.0,1.0,1,0,0,0,1,1
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,1.0,1.0,1.0,1,0,0,0,1,1

In [ ]:
df['verified']=pd.to_datetime(df['verified'])
df['booked']=pd.to_datetime(df['booked'])

<ipython-input-33-b1f76063b405>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['verified']=pd.to_datetime(df['verified'])
<ipython-input-33-b1f76063b405>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['booked']=pd.to_datetime(df['booked'])

In [ ]:
# Time taken for verfication
df['verified_time_min']=np.where(df['verified'].notna()&df['booked'].notna(),
np.maximum((df['verified']-df['booked']).dt.total_seconds()/60,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,First_SLA_Adherence,Second_SLA_Adherence,Latest_SLA_Adherence,Count,pre_store_pending,prebill,postShip_Pending,Store_Pushed,DSP_Assigned,verified_time_min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,0.0,1,0,0,0,1,0,0.250000
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,0.0,1,0,0,0,1,0,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,0.0,1,0,0,0,1,0,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,0.0,1,0,0,0,1,0,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,0.0,1,0,0,0,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1.0,1.0,1,0,0,0,1,1,NaN
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1.0,1.0,1.0,1,0,0,0,1,1,0.266667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1.0,1.0,1.0,1,0,0,0,1,1,NaN
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1.0,1.0,1.0,1,0,0,0,1,1,NaN
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1.0,1.0,1,0,0,0,1,1,NaN

In [ ]:
df['last_shc']= pd.to_datetime(df['last_shc'])
df['billed']= pd.to_datetime (df['billed'])

<ipython-input-35-4802cee33916>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['last_shc']= pd.to_datetime(df['last_shc'])
<ipython-input-35-4802cee33916>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['billed']= pd.to_datetime (df['billed'])

In [ ]:
# Created to track how much time order took for billing once it landed on store
df['Billed_time_min'] = np.where(df['billed'].notna() & df['last_shc'].notna(),
np.maximum((df['billed'] - df['last_shc']).dt.total_seconds() / 60,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Second_SLA_Adherence,Latest_SLA_Adherence,Count,pre_store_pending,prebill,postShip_Pending,Store_Pushed,DSP_Assigned,verified_time_min,Billed_time_min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,1,0,0,0,1,0,0.250000,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,1,0,0,0,1,0,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,1,0,0,0,1,0,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,1,0,0,0,1,0,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,0.0,1,0,0,0,1,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1.0,1,0,0,0,1,1,NaN,3.716667
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1.0,1.0,1,0,0,0,1,1,0.266667,11.433333
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1.0,1.0,1,0,0,0,1,1,NaN,1.433333
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1.0,1.0,1,0,0,0,1,1,NaN,58.100000
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1.0,1,0,0,0,1,1,NaN,2.866667

In [ ]:
df['firstpacked']=pd.to_datetime(df['firstpacked'])
df['billed']=pd.to_datetime(df['billed'])

<ipython-input-37-bbbc09c7d54c>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['firstpacked']=pd.to_datetime(df['firstpacked'])

In [ ]:
# Created to track how much time order took for rider assigment
df['DSP_Allocation_In_Min'] = np.where(df['billed'].notna() & df['firstpacked'].notna(),
np.maximum((df['firstpacked'] - df['billed']).dt.total_seconds() / 60,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Latest_SLA_Adherence,Count,pre_store_pending,prebill,postShip_Pending,Store_Pushed,DSP_Assigned,verified_time_min,Billed_time_min,DSP_Allocation_In_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,1,0,0,0,1,0,0.250000,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0.0,1,0,0,0,1,0,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,1,0,0,0,1,0,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,1,0,0,0,1,0,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0.0,1,0,0,0,1,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1,0,0,0,1,1,NaN,3.716667,0.200000
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1.0,1,0,0,0,1,1,0.266667,11.433333,0.183333
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1.0,1,0,0,0,1,1,NaN,1.433333,5.966667
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1.0,1,0,0,0,1,1,NaN,58.100000,0.166667
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1.0,1,0,0,0,1,1,NaN,2.866667,0.133333

In [ ]:
df['rider_reached_store'] = pd.to_datetime(df['rider_reached_store'])
df['last_ofd'] = pd.to_datetime(df['last_ofd'])

<ipython-input-39-e54c5eb42227>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['rider_reached_store'] = pd.to_datetime(df['rider_reached_store'])
<ipython-input-39-e54c5eb42227>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['last_ofd'] = pd.to_datetime(df['last_ofd'])

In [ ]:
df['RiderAssing_in_min']=np.where (df['rider_reached_store'].notna(),
np.maximum((df['last_ofd']- df['rider_reached_store']).dt.total_seconds()/60,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Count,pre_store_pending,prebill,postShip_Pending,Store_Pushed,DSP_Assigned,verified_time_min,Billed_time_min,DSP_Allocation_In_Min,RiderAssing_in_min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,1,0,0.250000,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,1,0,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,1,0,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,1,0,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0,0,1,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,NaN,3.716667,0.200000,4.733333
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,0.266667,11.433333,0.183333,3.733333
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,NaN,1.433333,5.966667,1.733333
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,0,0,0,1,1,NaN,58.100000,0.166667,1.516667
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,0,0,0,1,1,NaN,2.866667,0.133333,1.483333

In [ ]:
df['delivered']=pd.to_datetime(df['delivered'])
df['lastshipped']=pd.to_datetime(df['lastshipped'])

<ipython-input-41-ecd6f88f98ce>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['lastshipped']=pd.to_datetime(df['lastshipped'])

In [ ]:
#Created time in mintues using delivery and lastshipped timestamps
df['RiderDelivery_In_Min'] = np.where(df['delivered'].notna() & df['lastshipped'].notna(),
np.maximum ((df['delivered'] - df['lastshipped']).dt.total_seconds() / 60,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,pre_store_pending,prebill,postShip_Pending,Store_Pushed,DSP_Assigned,verified_time_min,Billed_time_min,DSP_Allocation_In_Min,RiderAssing_in_min,RiderDelivery_In_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0,0.250000,NaN,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1,NaN,3.716667,0.200000,4.733333,14.200000
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,0,1,1,0.266667,11.433333,0.183333,3.733333,8.666667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,0,1,1,NaN,1.433333,5.966667,1.733333,14.250000
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,0,1,1,NaN,58.100000,0.166667,1.516667,12.566667
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,0,1,1,NaN,2.866667,0.133333,1.483333,8.516667

In [ ]:
df.columns

Index(['orderid', 'cust_pin', 'SHOPID', 'store_city', 'customer_city_bucket',
       'store_type', 'City_Bucket', 'LATESTORDERSTATUS', 'systemDSP',
       'forwardDSP', 'pendencyFlag', 'pendencyType', 'orderDateXls',
       'firstTatDate', 'secondTatDate', 'created_ts_IST', 'booked',
       'rider_reached_store', 'verified', 'first_shc', 'last_shc', 'billed',
       'firstpacked', 'lastpacked', 'first_rts', 'last_rts', 'firstshipped',
       'lastshipped', 'first_ofd', 'last_ofd', 'first_attempted',
       'rider_reached_customer_gate', 'delivery_attempted', 'delivered',
       'cancelled', 'return_pending', 'return_requested', 'firstTAT',
       'secondTAT', 'latestTAT', 'order_Reattempt', 'is_Delivered',
       'is_cancelled', 'pending', 'Post_delivery_returns',
       'Formatted_created_date', 'create_to_f_tat_diff',
       'Created_to_F_TAT_Diff_0_to_2_hrs', 'Created_to_F_TAT_Diff_2_to_4_hrs',
       'four_8hrs', 'eight_24hrs', 'twentyfour_48hrs', 'greaterthan_48hrs',
       'NetDelivered', 'First_SLA_Adherence', 'Second_SLA_Adherence',
       'Latest_SLA_Adherence', 'Count', 'pre_store_pending', 'prebill',
       'postShip_Pending', 'Store_Pushed', 'DSP_Assigned', 'verified_time_min',
       'Billed_time_min', 'DSP_Allocation_In_Min', 'RiderAssing_in_min',
       'RiderDelivery_In_Min'],
      dtype='object')

In [ ]:
df['firstshipped']=pd.to_datetime(df['firstshipped'])
df['first_rts']=pd.to_datetime(df['first_rts'])

<ipython-input-44-fa68aba82a8a>:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['firstshipped']=pd.to_datetime(df['firstshipped'])
<ipython-input-44-fa68aba82a8a>:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['first_rts']=pd.to_datetime(df['first_rts'])

In [ ]:
#Created to track how much time order took to get picked up rider
df['Pickup_In_Min'] = np.where(df['firstshipped'].notna() & df['first_rts'].notna(),
np.maximum ((df['firstshipped'] - df['first_rts']).dt.total_seconds() / 60,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,prebill,postShip_Pending,Store_Pushed,DSP_Assigned,verified_time_min,Billed_time_min,DSP_Allocation_In_Min,RiderAssing_in_min,RiderDelivery_In_Min,Pickup_In_Min
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,0.250000,NaN,NaN,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,NaN,3.716667,0.200000,4.733333,14.200000,8.466667
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,0,1,1,0.266667,11.433333,0.183333,3.733333,8.666667,10.416667
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,0,1,1,NaN,1.433333,5.966667,1.733333,14.250000,8.616667
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,0,1,1,NaN,58.100000,0.166667,1.516667,12.566667,3.783333
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,0,1,1,NaN,2.866667,0.133333,1.483333,8.516667,4.000000

In [ ]:
df['delivered']=pd.to_datetime(df['delivered'])
df['billed']=pd.to_datetime(df['billed'])

In [ ]:
# Created time in hours using delievery and billed timestamps
df['O2D_In_Hour'] = np.where(df['delivered'].notna() & df['billed'].notna(),
np.maximum ((df['delivered'] - df['billed']).dt.total_seconds() / 3600,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,postShip_Pending,Store_Pushed,DSP_Assigned,verified_time_min,Billed_time_min,DSP_Allocation_In_Min,RiderAssing_in_min,RiderDelivery_In_Min,Pickup_In_Min,O2D_In_Hour
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,0.250000,NaN,NaN,NaN,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,1,NaN,3.716667,0.200000,4.733333,14.200000,8.466667,0.449722
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,0,1,1,0.266667,11.433333,0.183333,3.733333,8.666667,10.416667,0.447778
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,0,1,1,NaN,1.433333,5.966667,1.733333,14.250000,8.616667,0.560833
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,0,1,1,NaN,58.100000,0.166667,1.516667,12.566667,3.783333,0.279722
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,0,1,1,NaN,2.866667,0.133333,1.483333,8.516667,4.000000,0.293889

In [ ]:
df['last_ofd']=pd.to_datetime(df['last_ofd'])
df['rider_reached_store']=pd.to_datetime(df['rider_reached_store'])

In [ ]:
# Created store wait time in hours using last_ofd and riderreached store
df['store_wait_time'] = np.where(df['last_ofd'].notna() & df['rider_reached_store'].notna(),
np.maximum ((df['last_ofd'] - df['rider_reached_store']).dt.total_seconds() / 3600,0),np.nan)
df

,orderid,cust_pin,SHOPID,store_city,customer_city_bucket,store_type,City_Bucket,LATESTORDERSTATUS,systemDSP,forwardDSP,...,Store_Pushed,DSP_Assigned,verified_time_min,Billed_time_min,DSP_Allocation_In_Min,RiderAssing_in_min,RiderDelivery_In_Min,Pickup_In_Min,O2D_In_Hour,store_wait_time
0,1,380060,1,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,382007,2,Ahmedabad,Next 8 cities,Mid,Expansion,CANCELLED,NaN,NaN,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,382421,3,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,380061,4,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,382350,5,Ahmedabad,Next 8 cities,Small,Expansion,CANCELLED,NaN,NaN,...,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19996,603103,1429,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,1,NaN,3.716667,0.200000,4.733333,14.200000,8.466667,0.449722,0.078889
19996,19997,575003,1791,Mangalore,Others,Mid,Karaka - Other Cities,DELIVERED,EE,EEEE,...,1,1,0.266667,11.433333,0.183333,3.733333,8.666667,10.416667,0.447778,0.062222
19997,19998,533016,1424,KAKINADA,Others,Mid,South - Tier 2,DELIVERED,EE,EEEE,...,1,1,NaN,1.433333,5.966667,1.733333,14.250000,8.616667,0.560833,0.028889
19998,19999,452005,2238,Indore,Others,Mid,Expansion,DELIVERED,FF,FFFF,...,1,1,NaN,58.100000,0.166667,1.516667,12.566667,3.783333,0.279722,0.025278
19999,20000,603209,1428,KANCHIPURAM,Others,Mid,South - CHN Ops,DELIVERED,EE,EEEE,...,1,1,NaN,2.866667,0.133333,1.483333,8.516667,4.000000,0.293889,0.024722

In [ ]:
df.columns

Index(['orderid', 'cust_pin', 'SHOPID', 'store_city', 'customer_city_bucket',
       'store_type', 'City_Bucket', 'LATESTORDERSTATUS', 'systemDSP',
       'forwardDSP', 'pendencyFlag', 'pendencyType', 'orderDateXls',
       'firstTatDate', 'secondTatDate', 'created_ts_IST', 'booked',
       'rider_reached_store', 'verified', 'first_shc', 'last_shc', 'billed',
       'firstpacked', 'lastpacked', 'first_rts', 'last_rts', 'firstshipped',
       'lastshipped', 'first_ofd', 'last_ofd', 'first_attempted',
       'rider_reached_customer_gate', 'delivery_attempted', 'delivered',
       'cancelled', 'return_pending', 'return_requested', 'firstTAT',
       'secondTAT', 'latestTAT', 'order_Reattempt', 'is_Delivered',
       'is_cancelled', 'pending', 'Post_delivery_returns',
       'Formatted_created_date', 'create_to_f_tat_diff',
       'Created_to_F_TAT_Diff_0_to_2_hrs', 'Created_to_F_TAT_Diff_2_to_4_hrs',
       'four_8hrs', 'eight_24hrs', 'twentyfour_48hrs', 'greaterthan_48hrs',
       'NetDelivered', 'First_SLA_Adherence', 'Second_SLA_Adherence',
       'Latest_SLA_Adherence', 'Count', 'pre_store_pending', 'prebill',
       'postShip_Pending', 'Store_Pushed', 'DSP_Assigned', 'verified_time_min',
       'Billed_time_min', 'DSP_Allocation_In_Min', 'RiderAssing_in_min',
       'RiderDelivery_In_Min', 'Pickup_In_Min', 'O2D_In_Hour',
       'store_wait_time'],
      dtype='object')

In [ ]:
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/My Drive/ouput.xlsx'
df.to_excel(file_path, index=False)

Mounted at /content/drive